import PDFDocument from 'pdfkit'

export interface ReportData {
  title: string
  description?: string
  generatedBy: string
  generatedAt: Date
  data: any[]
  filters?: Record<string, any>
}

export class PDFGenerator {
  private doc: PDFKit.PDFDocument

  constructor() {
    this.doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    })
  }

  private addHeader(title: string, subtitle?: string) {
    this.doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .text(title, 50, 50)
      .moveDown(0.5)

    if (subtitle) {
      this.doc
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#666666')
        .text(subtitle)
        .moveDown(1)
    }

    // Add a line under the header
    this.doc
      .strokeColor('#cccccc')
      .lineWidth(1)
      .moveTo(50, this.doc.y)
      .lineTo(545, this.doc.y)
      .stroke()
      .moveDown(1)
  }

  private addFooter() {
    const bottom = this.doc.page.height - 50
    this.doc
      .fontSize(10)
      .fillColor('#666666')
      .text(
        `Generated on ${new Date().toLocaleDateString()} | Alumni Tracker System`,
        50,
        bottom,
        { align: 'center' }
      )
  }

  private addMetadata(reportData: ReportData) {
    this.doc
      .fontSize(10)
      .fillColor('#666666')
      .text(`Generated by: ${reportData.generatedBy}`, { align: 'right' })
      .text(`Generated at: ${reportData.generatedAt.toLocaleString()}`, { align: 'right' })
      .moveDown(1)

    if (reportData.description) {
      this.doc
        .fontSize(11)
        .fillColor('#333333')
        .text(reportData.description)
        .moveDown(1)
    }

    if (reportData.filters && Object.keys(reportData.filters).length > 0) {
      this.doc
        .fontSize(10)
        .fillColor('#666666')
        .text('Applied Filters:', { underline: true })
      
      Object.entries(reportData.filters).forEach(([key, value]) => {
        if (value) {
          this.doc.text(`${key}: ${value}`)
        }
      })
      this.doc.moveDown(1)
    }
  }

  generateAlumniReport(reportData: ReportData): Buffer {
    this.addHeader(reportData.title, 'Alumni Directory Report')
    this.addMetadata(reportData)

    // Summary stats
    const totalAlumni = reportData.data.length
    const employedCount = reportData.data.filter(a => 
      a.employments.some((e: any) => e.isCurrent)
    ).length
    const employmentRate = totalAlumni > 0 ? (employedCount / totalAlumni * 100).toFixed(1) : '0'

    this.doc
      .fontSize(12)
      .fillColor('#333333')
      .font('Helvetica-Bold')
      .text('Summary Statistics', { underline: true })
      .font('Helvetica')
      .text(`Total Alumni: ${totalAlumni}`)
      .text(`Currently Employed: ${employedCount}`)
      .text(`Employment Rate: ${employmentRate}%`)
      .moveDown(1)

    // Alumni list
    this.doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Alumni Directory', { underline: true })
      .moveDown(0.5)

    reportData.data.forEach((alumni, index) => {
      if (this.doc.y > 700) {
        this.doc.addPage()
      }

      const currentJob = alumni.employments.find((e: any) => e.isCurrent)
      
      this.doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#333333')
        .text(`${index + 1}. ${alumni.firstName} ${alumni.lastName}`)
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#666666')
        .text(`   Course: ${alumni.course} | Class of ${alumni.yearGraduated}`)
        .text(`   Student ID: ${alumni.studentId}`)

      if (currentJob) {
        this.doc.text(`   Current Position: ${currentJob.position} at ${currentJob.company}`)
        if (currentJob.location) {
          this.doc.text(`   Location: ${currentJob.location}`)
        }
      } else {
        this.doc.text('   Employment Status: Seeking Opportunities')
      }

      if (alumni.currentLocation) {
        this.doc.text(`   Current Location: ${alumni.currentLocation}`)
      }

      this.doc.moveDown(0.5)
    })

    this.addFooter()
    this.doc.end()

    return this.doc as any
  }

  generateEmploymentReport(reportData: ReportData): Buffer {
    this.addHeader(reportData.title, 'Employment Statistics Report')
    this.addMetadata(reportData)

    // Calculate employment statistics
    const totalAlumni = reportData.data.length
    const employedAlumni = reportData.data.filter(a => 
      a.employments.some((e: any) => e.isCurrent)
    )
    const unemployedAlumni = totalAlumni - employedAlumni.length

    // Industry breakdown
    const industryCount: Record<string, number> = {}
    employedAlumni.forEach(alumni => {
      const currentJob = alumni.employments.find((e: any) => e.isCurrent)
      if (currentJob?.industry) {
        industryCount[currentJob.industry] = (industryCount[currentJob.industry] || 0) + 1
      }
    })

    // Company breakdown
    const companyCount: Record<string, number> = {}
    employedAlumni.forEach(alumni => {
      const currentJob = alumni.employments.find((e: any) => e.isCurrent)
      if (currentJob?.company) {
        companyCount[currentJob.company] = (companyCount[currentJob.company] || 0) + 1
      }
    })

    // Summary
    this.doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Employment Overview', { underline: true })
      .font('Helvetica')
      .text(`Total Alumni: ${totalAlumni}`)
      .text(`Currently Employed: ${employedAlumni.length} (${((employedAlumni.length / totalAlumni) * 100).toFixed(1)}%)`)
      .text(`Seeking Opportunities: ${unemployedAlumni} (${((unemployedAlumni / totalAlumni) * 100).toFixed(1)}%)`)
      .moveDown(1)

    // Industry breakdown
    if (Object.keys(industryCount).length > 0) {
      this.doc
        .font('Helvetica-Bold')
        .text('Industry Distribution', { underline: true })
        .font('Helvetica')

      Object.entries(industryCount)
        .sort(([,a], [,b]) => b - a)
        .forEach(([industry, count]) => {
          const percentage = ((count / employedAlumni.length) * 100).toFixed(1)
          this.doc.text(`${industry}: ${count} alumni (${percentage}%)`)
        })
      
      this.doc.moveDown(1)
    }

    // Top employers
    if (Object.keys(companyCount).length > 0) {
      this.doc
        .font('Helvetica-Bold')
        .text('Top Employers', { underline: true })
        .font('Helvetica')

      Object.entries(companyCount)
        .sort(([,a], [,b]) => b - a)
        .slice(0, 10)
        .forEach(([company, count]) => {
          this.doc.text(`${company}: ${count} alumni`)
        })
    }

    this.addFooter()
    this.doc.end()

    return this.doc as any
  }

  generateYearReport(reportData: ReportData): Buffer {
    this.addHeader(reportData.title, 'Graduation Year Analysis Report')
    this.addMetadata(reportData)

    // Group by graduation year
    const yearGroups: Record<number, any[]> = {}
    reportData.data.forEach(alumni => {
      if (!yearGroups[alumni.yearGraduated]) {
        yearGroups[alumni.yearGraduated] = []
      }
      yearGroups[alumni.yearGraduated].push(alumni)
    })

    // Summary by year
    this.doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Graduation Year Statistics', { underline: true })
      .moveDown(0.5)

    const sortedYears = Object.keys(yearGroups).map(Number).sort((a, b) => b - a)
    
    sortedYears.forEach(year => {
      const yearAlumni = yearGroups[year]
      const employed = yearAlumni.filter(a => a.employments.some((e: any) => e.isCurrent)).length
      const employmentRate = ((employed / yearAlumni.length) * 100).toFixed(1)

      this.doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .text(`Class of ${year}`)
        .font('Helvetica')
        .fontSize(10)
        .text(`   Total Alumni: ${yearAlumni.length}`)
        .text(`   Currently Employed: ${employed} (${employmentRate}%)`)
        .moveDown(0.5)
    })

    this.addFooter()
    this.doc.end()

    return this.doc as any
  }
}
